version: "3.8"
services:
  oauthproxy:
    image: "quay.io/oauth2-proxy/oauth2-proxy:latest"
    depends_on:
      - gallery
    networks:
      oauth2-proxy:
    ports:
      - "8230:4180"
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: <cookie>
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_CLIENT_ID: <client_id>
      OAUTH2_PROXY_CLIENT_SECRET: <client_secret>
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: "/authenticated_emails_files/family"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAMS: "http://gallery:8000"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
    volumes:
      - /etc/oauth2-proxy/authenticated_emails_files:/authenticated_emails_files
  gallery:
    image: "mindflavor/nas_gallery:latest"
    networks:
      oauth2-proxy: 
    user: "149:65534"
    volumes:
      - /your_folder:/mnt/nas
      - /etc/nas_gallery:/etc/nas_gallery
      - /ssd/nas_gallery:/ssd/nas_gallery
      - /var/log/nas_gallery:/var/log/nas_gallery
      
networks:
  oauth2-proxy:
      external: true
     
