log_file = "/var/log/nas_gallery/nas_gallery.log"
log_level = "Info"
audit_file = "/var/log/nas_gallery/audit.log"
static_site_path = "/var/www/nas_gallery/"
thumb_folder_path = "/tmp"
prometheus_metrics_port = true

[[groups]]
name = "Sample"
members_email = ["forced.user@foo.bar"]

[[folders]]
path = "/mnt/nas"
inheritable = true
breaks_inheritance = true
allowed = ["#Sample"]
denied = []

